### ISSUE TITLE
Trouble getting docker image to work

### ISSUE THREAD

**Issue by Froghut** [FoxUSA/StoreDown#5]
I set up couchdb config as described in th einstall doc, When I try to set the connection in StoreDown (using the ip of the couchdb instance, port 5984 and DB name "StoreDown") I get the message "Replication complete" after a while.
But when I try to add a new Item I just get an empty "Item Editor" page with a Save and Discard Button. I also tried importing the demo data which gave me the message that 5 Items were imported, but there were no items in Item List etc.
Neither the StoreDown container nor the couchdb container give me any error messages (in docker logs) during the whole process.
Any help would be appreciated!

**Comment by Ksdmg** [comment]
Yep I have exactly the same issue!

**Comment by FoxUSA** [comment]
Can you bring up the developer tools in your browser(Most of the time its F12 to open) and see if there are any error messages.

**Comment by FoxUSA** [comment]
The other thing that comes to mind is StoreDown is built in a weird way. All the fields are configurable, when you log in without a DB it uses a default config but when you log into a DB it expects one to be there.

Can you open the Configuration and paste in the [default config](https://github.com/FoxUSA/StoreDown/blob/master/src/views/Login.vue#L58)?
```
---
dataDefinition:
  - displayName: Core info
    color: light-blue darken-2 #pick colors from https://v15.vuetifyjs.com/en/framework/colors
    fields:
      - name: _id
        displayName: ID
        type: string
        disabled: true
        showInTree: true
        size: 12
      - name: idLabeled
        displayName: Item labeled with ID
        type: boolean
        color: red
      - name: name
        displayName: Name
        type: string
        showInTree: true
      - name: location
        displayName: Location
        type: path
        size: 12
        prefixes:
          box01: House1/Room1/
        #showInTree: true
      - name: description
        displayName: Description
        type: string #TODO MarkDown
        hideInList: true
        size: 12
  - displayName: Status
    color: indigo darken-2
    fields:
      - name: status
        displayName: Status
        type: libraryStyleStatus #Checkin checkout
        size: 12
        showInTree: true
      - name: lastModified
        displayName: Last Modified
        type: lastModified
      - name: lastTouchDate
        displayName: Last touch date
        type: lastDate
        dateFields:
          - name: status
            type: libraryStyleStatus
          - name: acquireDate
      - name: holdReason
        displayName: Hold reason
        type: string
        hideInList: true
        size: 12
  - displayName: Metadata
    color: light-blue accent-4
    fields:
      - name: tags
        displayName: Tags
        type: list
        size: 12
      - name: code
        displayName: Code
        type: list
        listType: upc
        size: 12
        hideInList: true
  - displayName: Facts
    color: light-blue lighten-3
    size: 12
    fields:
      - name: weight
        displayName: Weight
        type: string
      - name: dimensions
        displayName: Dimensions
        type: string
      - name: expirationDate
        displayName: Expiration Date
        type: date
      - name: imageURLs
        displayName: Image URLs
        type: list
        listType: link
        hideInList: true
      - name: manualPaths
        displayName: Manual paths
        type: list
        listType: link
        hideInList: true
  - displayName: Acquisition
    color: light-blue accent-3
    fields:
      - name: acquiredFrom
        displayName: Acquired from
        type: string
      - name: pricePaid
        displayName: Price paid without tax
        type: string
      - name: receiptURLS
        displayName: Receipt urls
        type: list
        listType: link
        hideInList: true
        size: 12
      - name: acquireDate
        displayName: Acquired date
        type: date
      - name: manufacturer
        displayName: Manufacturer
        type: string
      - name: warranty
        displayName: Warranty term
        type: string
        hideInList: true
```
